stages:
  - analysis
  - build

before_script:
  - hostname
  - whoami
# - pwd
  - git submodule sync --recursive
  - git submodule update --init --recursive

analysis-cppcheck:
  stage: analysis
  artifacts:
     name: analysis-cppcheck-logs
     when: always
     paths:
       - cppcheck/
  tags:
    - cppcheck
  script:
    - ./ci/analysis-cppcheck.sh

build-linux-gcc:
  stage: build
  tags:
   - linux
  script:
    - ./ci/build-linux-gcc.sh

build-linux-clang:
  stage: build
  tags:
   - linux
  script:
    - ./ci/build-linux-clang.sh

build-linux-gcc-4.8:
  stage: build
  tags:
   - linux
  script:
    - ./ci/build-linux-gcc-4.8.sh

build-linux-icpc:
  stage: build
  tags:
   - linux
  script:
    - ./ci/build-linux-icpc.sh

build-windows-gcc:
  stage: build
  tags:
   - windows
  script:
    - ./ci/build-windows-gcc.bat

build-windows-msvc:
  stage: build
  tags:
   - windows
  script:
    - ./ci/build-windows-msvc.bat

build-mac-osx-clang:
  stage: build
  tags:
   - mac-osx
  script:
    - ./ci/build-mac-osx-clang.sh